### PR TITLE
Fix Jetstream Source Reconnection + Lost messages

### LINKED ISSUE #62: Bug: Source connector stop working after NATS reconnection
### Bug description

After the NATS system recreates a connection, the connector ceases to function. This issue has been observed consistently following each instance of NATS connection recreation. Consequently, data transmission and communication processes stop working, leading to major operational setbacks.

### Steps to reproduce

1. Start the connector and NATS server.
2. Create a pipeline file with NATS Jetstream as the source and `log` as the destination.
3. Use NATS benchmark to create some load: `nats bench test --js --pub 1 --size 16 --msgs 10`
4. Run conduit and observe logs of messages received working.
5. Stop NATS server
6. Stop NATS benchmark
7. Start NATS server
8. Start NATS benchmark
9. Observe logs of messages received NOT working.

### Version

0.3.1

### PR DESCRIPTION
**Pull request by nassor**
### Description

Changes:
- Package refactoring: they are now following a hierarchical and flat organization and keeping most of the code inside `internal` because they are meant to be imported by anything that is not the connector itself.
- The connector is now more reliable because it auto reconnects in case of network issues
- Moves source connector from push-based to pull-based, so now the connector will request more data from NATS instead, allowing NATS to set the pace of consumption. That will also fix a bug where, during reconnection, some messages would be lost.
- Updated documentation to reflect changes.
- **Update:** I removed the destination reconnection changes. I will make a separated PR for those.

Fixes #62 

### Quick checks:

- [X] I have followed the [Code Guidelines](https://github.com/ConduitIO/conduit/blob/main/docs/code_guidelines.md).
- [X] There is no other [pull request](https://github.com/conduitio-labs/conduit-connector-nats-jetstream/pulls) for the same update/change.
- [X] I have written unit tests.
- [X] I have made sure that the PR is of reasonable size and can be easily reviewed.

### CODE REVIEW

File: internal/destination/writer.go [hunk 1]
```diff
@@ -90,3 +90,12 @@ func (w *Writer) Close() error {
 
 	return nil
 }
+
+// Reconnect rebuilds jetstream context
```
Comment (janelletavares) [inline internal/destination/writer.go:94]:
```suggestion
// Reconnect rebuilds jetstream context.
```

File: internal/destination/writer.go [hunk 2]
```diff
@@ -90,3 +90,12 @@ func (w *Writer) Close() error {
...
+func (w *Writer) Reconnect(conn *nats.Conn) (err error) {
+	w.mu.Lock()
+	defer w.mu.Unlock()
+
+	w.jetstream, err = conn.JetStream()
+	return
```
Comment (janelletavares) [inline internal/destination/writer.go:100]:
```suggestion

	return err
```

File: internal/source/iterator.go [hunk 3]
```diff
@@ -25,26 +25,30 @@ import (
 	"github.com/nats-io/nats.go"
 )
 
-// heartbeatTimeout is a default heartbeat timeout for push consumers.
-const heartbeatTimeout = 2 * time.Second
+// fetchSize is always 1 because conduit expects only one Record
```
Comment (janelletavares) [inline internal/source/iterator.go:28]:
```suggestion
// fetchSize is always 1 because conduit expects only one Record.
```

File: internal/source/iterator.go [hunk 4]
```diff
@@ -88,101 +92,142 @@ func (p IteratorParams) getSubscribeOptions() ([]nats.SubOpt, error) {
...
+	}
+
+	ci, err := i.subscription.ConsumerInfo()
+	if err != nil {
+		sdk.Logger(ctx).
+			Error().
+			Err(err).
+			Interface("consumer_info", ci).
+			Send()
+		return false
```
Comment (janelletavares) [inline internal/source/iterator.go:144]:
```suggestion

		return false
```

File: internal/source/iterator.go [hunk 5]
```diff
@@ -88,101 +92,142 @@ func (p IteratorParams) getSubscribeOptions() ([]nats.SubOpt, error) {
...
 }
 
+func (i *Iterator) unAckAll() error {
+	// explicity not acking unackedMessages
+	for _, msg := range i.unackMessages {
+		if err := msg.Nak(); err != nil {
+			return fmt.Errorf("not ack (when stopping): %w", err)
+		}
+	}
+	return nil
```
Comment (janelletavares) [inline internal/source/iterator.go:228]:
```suggestion

	return nil
```

File: internal/source/iterator.go [hunk 6]
```diff
@@ -246,14 +270,9 @@ func (i *Iterator) messageToRecord(msg *nats.Msg) (sdk.Record, error) {
 }
 
 // getMessagePosition returns a position of a message in the form of sdk.Position.
-func (i *Iterator) getMessagePosition(msg *nats.Msg) (sdk.Position, error) {
-	metadata, err := msg.Metadata()
-	if err != nil {
-		return nil, fmt.Errorf("get message metadata: %w", err)
-	}
-
+func (i *Iterator) getMessagePosition(msg *nats.Msg, metadata *nats.MsgMetadata) (sdk.Position, error) {
```
Comment (janelletavares) [inline internal/source/iterator.go:273]:
```suggestion
func (i *Iterator) getMessagePosition(_ *nats.Msg, metadata *nats.MsgMetadata) (sdk.Position, error) {
```

File: internal/source/source.go [hunk 7]
```diff
@@ -107,7 +119,7 @@ func (s *Source) Parameters() map[string]sdk.Parameter {
 			Description: "A consumer name.",
 		},
 		ConfigKeyDeliverSubject: {
-			Default:     "<durable>.conduit",
+			Default:     "<durable>.conduit", //FIXME it send the way that it is
```
Comment (janelletavares) [inline internal/source/source.go:122]:
```suggestion
			Default:     "<durable>.conduit", // FIXME it send the way that it is
```

File: internal/destination/destination.go [hunk 8]
```diff
@@ -150,6 +142,27 @@ func (d *Destination) Open(ctx context.Context) error {
...
+		}
+	}))
+	conn.SetReconnectHandler(internal.ReconnectCallback(ctx, func(c *nats.Conn) {
+		if err := d.Open(ctx); err != nil {
+			sdk.Logger(ctx).
+				Error().
+				Err(err).
+				Msg("no able to overwrite the destination writer (reconnect)")
+		}
+	}))
```
Comment (hariso) [inline internal/destination/destination.go:162]: So while we are reconnecting it's possible that a new record comes in and the destination tries to write it. At the same time, the reconnect logic will overwrite the `writer` field. Won't this cause a race condition? Or am I misunderstanding something?

File: internal/destination/writer.go [hunk 9]
```diff
@@ -90,3 +90,12 @@ func (w *Writer) Close() error {
 
 	return nil
 }
+
+// Reconnect rebuilds jetstream context
+func (w *Writer) Reconnect(conn *nats.Conn) (err error) {
```
Comment (hariso) [inline internal/destination/writer.go:95]: Where is this method actually being used?

**Review by hariso — COMMENTED** [review]
Thanks for the excellent work, Nassor!

File: internal/source/iterator.go (hunk 6 above)
Comment (hariso) [reply internal/source/iterator.go:273]: Or maybe just remove the param completely?

File: internal/source/source.go [hunk 10]
```diff
@@ -169,13 +175,27 @@ func (s *Source) Open(ctx context.Context, position sdk.Position) error {
 		return fmt.Errorf("init jetstream iterator: %w", err)
 	}
 
+	// Async handlers & callbacks
+	conn.SetErrorHandler(internal.ErrorHandlerCallback(ctx))
+	conn.SetDisconnectErrHandler(internal.DisconnectErrCallback(ctx, func(c *nats.Conn) {
+		s.iterator.unAckAll()
+		s.iterator.jetstream.UpdateConsumer(s.iterator.params.Stream, &nats.ConsumerConfig{
```
Comment (hariso) [inline internal/source/source.go:182]: What's the intention behind this?

File: internal/source/source.go [hunk 11]
```diff
@@ -169,13 +175,27 @@ func (s *Source) Open(ctx context.Context, position sdk.Position) error {
 		return fmt.Errorf("init jetstream iterator: %w", err)
 	}
 
+	// Async handlers & callbacks
+	conn.SetErrorHandler(internal.ErrorHandlerCallback(ctx))
+	conn.SetDisconnectErrHandler(internal.DisconnectErrCallback(ctx, func(c *nats.Conn) {
```
Comment (hariso) [inline internal/source/source.go:180]: I'm thinking about disconnects and reconnects in this way: disconnect = stop source iterator, reconnect = start source iterator. If that's correct, then I think that should be reflected through code, so we call Iterator.Stop() here.

File: internal/destination/destination.go (hunk 8 above)
Comment (nassor) [reply internal/destination/destination.go:162]: With these changes, we moved to pull mode instead of push mode. NATS no longer pushes messages to the connector; it pushes to a consumer queue from which the connector will pull.

Reference: https://docs.nats.io/nats-concepts/jetstream/consumers

File: internal/destination/writer.go (hunk 9 above)
Comment (nassor) [reply internal/destination/writer.go:95]: It is not anymore, I will remove it.

File: internal/source/source.go (hunk 10 above)
Comment (nassor) [reply internal/source/source.go:182]: https://docs.nats.io/running-a-nats-service/nats_admin/jetstream_admin/consumers#stream-vs-consumer-sequence-numbers

The consumer count gets zeroed when reconnects. The Stream counter still persists.

File: internal/destination/destination.go (hunk 8 above)
Comment (hariso) [reply internal/destination/destination.go:162]: Thanks for the clarification of that part. What I meant is: while we are reconnecting, it's possible that the destination connector receives a record for writing.

Comment (nassor) [reply internal/destination/destination.go:162]: If the rewrite fails, the message will not be acknowledged, and NATS will re-emit eventually, right?

Comment (nassor) [reply internal/destination/destination.go:162]: Another alternative would be to have one connection for the source & destination. What do you think?

Comment (hariso) [reply internal/destination/destination.go:162]: It's possible we're not on the same page... My concern was this field, [Destination.writer](https://github.com/conduitio-labs/conduit-connector-nats-jetstream/blob/6ab431b27502a45c612fb1d7e18bbe809e6a8d47/internal/destination/destination.go#L33).

Let's assume this: `Destination.Write()` is called. It will use `Destination.writer` to write the record.

At the same time, we try to reconnect to NATS. The reconnection code will try to overwrite the `Destination.writer` field, which is at the same time being used to write a record.

Comment (nassor) [reply internal/destination/destination.go:162]: I see what you are saying. The `Open` is also not recreating the jetstream context. I will remove the Destination changes from this PR and make another one for those.

Comment (nassor) [reply internal/destination/destination.go]: Removed.

Comment (hariso) [reply internal/destination/destination.go]: :+1:

File: internal/source/source.go (hunk 11 above)
Comment (nassor) [reply internal/source/source.go:180]: Now that [we move from storing the consumer sequence to storing the stream sequence](https://github.com/conduitio-labs/conduit-connector-nats-jetstream/pull/68/commits/7c53489a1b3ccafb57e36c93ead80f1b791e636c), that is now correct. Send a PR to fix it.

Comment (hariso) [reply internal/source/source.go:180]: Gotcha... I believe that those duplicates would be a surprise and an unexpected behavior. Connectors generally do their best to just resume from where they stopped. Do we have to work with the stream sequence in order to fix the bug?

Comment (nassor) [reply internal/source/source.go:180]: The acceptance tests bug to be more precise. Using the consumer sequence can add duplication (because Jetstream's expectation is at least once, and it will send the extras message even if messages are in flight in case of network failures, and It will also reset the consumer sequence in case of reconnection (they keeping the already ack stream sequence number in the correct place)

Comment (nassor) [reply internal/source/source.go:180]: And, duplicated records can still exist because Jetstream consumers will only guarantee at least once delivery.

File: acceptance_test.go [hunk 12]
```diff
@@ -51,6 +52,7 @@ func TestAcceptance(t *testing.T) {
 				SourceConfig:      cfg,
 				DestinationConfig: cfg,
 				BeforeTest:        beforeTest(cfg),
+				Skip:              []string{"ResumeAtPositionCDC"},
```
Comment (hariso) [inline acceptance_test.go:55]: Nitpick: if you could add a comment mentioning why we're skipping this and/or a GitHub issue for that, that would be great.

File: internal/source/iterator.go [hunk 13]
```diff
@@ -53,8 +57,8 @@ type IteratorParams struct {
 	AckPolicy      nats.AckPolicy
 }
 
-// getSubscribeOptions returns a NATS subscribe options based on the IteratorParams's fields.
-func (p IteratorParams) getSubscribeOptions() ([]nats.SubOpt, error) {
+// generateConsumerConfig returns a NATS subscribe options based on the IteratorParams's fields.
+func (p IteratorParams) getSubscriberOpts(ctx context.Context) ([]nats.SubOpt, error) {
```
Comment (hariso) [inline internal/source/iterator.go:61]: Nitpick: the comment mentions a different function name.

File: internal/source/iterator.go [hunk 14]
```diff
@@ -88,97 +92,140 @@ func (p IteratorParams) getSubscribeOptions() ([]nats.SubOpt, error) {
...
+func NewIterator(ctx context.Context, nc natsClient, params IteratorParams) (*Iterator, error) {
+	i := &Iterator{
+		mu:     sync.RWMutex{},
+		params: params,
+		nc:     nc,
 	}
 
-	subscribeOpts, err := params.getSubscribeOptions()
+	var err error
+	// i.messages = make(chan *nats.Msg, i.params.BufferSize)
```
Comment (hariso) [inline internal/source/iterator.go:111]: Shall we remove this?

File: internal/source/source.go [hunk 15]
```diff
@@ -198,6 +217,9 @@ func (s *Source) Teardown(context.Context) error {
 		if err := s.iterator.Stop(); err != nil {
 			return fmt.Errorf("stop iterator: %w", err)
 		}
+
+		// closing nats connection
+		s.nc.Close()
```
Comment (hariso) [inline internal/source/source.go:222]: Maybe do this as part of `iterator.Stop()`? That way, the source will only be talking to the iterator only and doesn't need to go to the "lower level", i.e. the client?

**Review by hariso — APPROVED** [review]

File: internal/source/source.go (hunk 15 above)
Comment (nassor) [reply internal/source/source.go:222]: I do prefer to keep closing the connection [where we open it](https://github.com/conduitio-labs/conduit-connector-nats-jetstream/pull/68/files#diff-31f0dc97cfd1c9aaef8c514393a23f48a8fc8a6b2c34217a7b0d3e3d9edbd0cfR158). The iterator is responsible for managing the connection context and iterating the data.

File: internal/source/iterator.go (hunk 13 above)
Comment (nassor) [reply internal/source/iterator.go:61]: Good catch!

File: acceptance_test.go (hunk 12 above)
Comment (nassor) [reply acceptance_test.go]: With the last changes, that was not necessary anymore. I removed it.
