### PR TITLE
Fix: destination reconnection

### LINKED ISSUE #73: Bug: Destination connector stop working after NATS reconnection
### Bug description

After the NATS system recreates a connection, the destination connector ceases to function by not being able to write to the new nats connection.

### Steps to reproduce

* Start the connector and NATS server.
* Create a pipeline file with NATS Jetstream as the source and destination
* Run `nats bench test --js --storage=memory --pub 1 --size 32 --msgs=200000` to send msgs to NATS
* Run conduit and observe by running `nats bench test --js --sub=1 --pull` 
* Stop NATS server
* Stop NATS benchmark
* Start NATS server
* Send more messages
* Start NATS benchmark
* Observe logs of messages that stop reaching the destination.

### Version

v0.3.1

### PR DESCRIPTION
**Pull request by nassor**
### Description

Added capabilities for the connector to start, stop and restart writes due to reconnections.

Fixes #73 

### Quick checks:

- [X] I have followed the [Code Guidelines](https://github.com/ConduitIO/conduit/blob/main/docs/code_guidelines.md).
- [X] There is no other [pull request](https://github.com/conduitio-labs/conduit-connector-nats-jetstream/pulls) for the same update/change.
- [X] I have written unit tests.
- [X] I have made sure that the PR is of reasonable size and can be easily reviewed.

### CODE REVIEW

File: internal/destination/destination.go [hunk 1]
```diff
@@ -131,29 +135,44 @@ func (d *Destination) Open(ctx context.Context) error {
...
+		return fmt.Errorf("init jetstream writer: %w", err)
+	}
+
 	return nil
 }
 
 // Write writes a record into a Destination.
 func (d *Destination) Write(_ context.Context, records []sdk.Record) (int, error) {
+	if !d.nc.IsConnected() {
+		return -1, errWriteUnavailable
```
Comment (lovromazgon) [inline internal/destination/destination.go:173]: Returning an error from `Write` will cause the pipeline to stop, I don't think this is the behavior we're aiming for, right? IIUC we rather want to wait until we reconnect (or the context gets cancelled) and write the records at that point.

Also, the returned integer represents the number of successfully written records, that's how Conduit knows how many records to ack / nack, if no records were written it should return 0.

Comment (nassor) [reply internal/destination/destination.go:173]: Ok, changing to Zero.

Question: if a write fails, does Conduit retries that?

File: internal/source/source.go [hunk 2]
```diff
@@ -215,7 +208,13 @@ func (s *Source) Ack(_ context.Context, position sdk.Position) error {
 func (s *Source) Teardown(context.Context) error {
 	if s.iterator != nil {
 		if err := s.iterator.Stop(); err != nil {
-			return fmt.Errorf("stop iterator: %w", err)
+			return fmt.Errorf("stop source: %w", err)
+		}
+	}
+
+	if s.nc != nil {
+		if err := s.nc.Drain(); err != nil {
```
[the remark this answers is not in the document]
Comment (nassor) [reply internal/source/source.go:216]: Ok, that answer the biggest question that I had last week.

File: internal/destination/destination.go (hunk 1 above)
Comment (lovromazgon) [reply internal/destination/destination.go:173]: No, Conduit is pretty strict this way, if it gets an error it stops the pipeline. The good news is the connector can block as long as it wants in `Write` as long it respects the context. So if the context gets cancelled while it's waiting for the reconnection, then it should return an error, which will tell Conduit that the messages didn't get written and they will be nacked.

File: internal/destination/destination.go [hunk 3]
```diff
@@ -131,29 +135,44 @@ func (d *Destination) Open(ctx context.Context) error {
...
+	}
+
 	return nil
 }
 
 // Write writes a record into a Destination.
 func (d *Destination) Write(_ context.Context, records []sdk.Record) (int, error) {
+	if !d.nc.IsConnected() {
+		return 0, errWriteUnavailable
+	}
```
Comment (lovromazgon) [inline internal/destination/destination.go:174]: This problem still exists, I'm pretty sure this will cause the pipeline to stop with an error if Conduit tries to write a record while the connector is reconnecting (not the behavior we want, right?). We should block here until the connection is established _or_ until the context is canceled, whatever happens first. See for example how we are doing this in the [grpc-client connector](https://github.com/conduitio-labs/conduit-connector-grpc-client/pull/9/files#diff-b0e314d1e24c22a62ecb712e94913d77bed15abfd75e80a0b61189c0abe17453R198-R222).

Comment (nassor) [reply internal/destination/destination.go]: I added a retry/wait logic around the function.

File: internal/destination/destination.go [hunk 4]
```diff
@@ -168,18 +170,34 @@ func (d *Destination) Open(ctx context.Context) error {
...
+	attempts := 0
+	recorded := 0
+	for _, record := range records {
+		attempts++
+
+		select {
+		case <-timeout.Done():
+			return recorded, errWriteTimeout
+		default:
+			if err := d.writer.Write(record); err != nil {
```
Comment (lovromazgon) [inline internal/destination/destination.go:186]: I'm thinking if we should really retry for all errors, or rather choose a subset that we know we can recover from?

**Review by lovromazgon — COMMENTED** [review]
I think we're almost there 👍

File: internal/destination/destination.go (hunk 4 above)
Comment (nassor) [reply internal/destination/destination.go:186]: Retry for a subset means we must keep revising the NATS driver repeatedly. We could also define the ones we want to avoid retrying, but those could also change over time. 

And they are hard to pick, authentication errors, for example, could happen because of bit flipping in the network.

File: internal/destination/destination.go [hunk 5]
```diff
@@ -168,18 +170,34 @@ func (d *Destination) Open(ctx context.Context) error {
...
-func (d *Destination) Write(_ context.Context, records []sdk.Record) (int, error) {
-	if !d.nc.IsConnected() {
-		return 0, errWriteUnavailable
-	}
-
-	for i, record := range records {
-		if err := d.writer.Write(record); err != nil {
-			return i, fmt.Errorf("write: %w", err)
+func (d *Destination) Write(ctx context.Context, records []sdk.Record) (int, error) {
+	timeout, cancel := context.WithTimeout(ctx, d.config.RetryWait*time.Duration(d.config.RetryAttempts))
```
[the remark this answers is not in the document]
Comment (nassor) [reply internal/destination/destination.go:174]: I am changing the connector to set defaults if values are set to zero. Reasoning [with opinion]: If it was just pure NATS, not Jetstream, fire-and-forget is a desirable feature, but it is not the case for Jetstream.

We have a situation of a middle-man (connector) who can't rely on the host (conduit:  fires the write command and puts it in a waiting group, but doesn't timeout) or the NATS server where we don't have how to know which version and that could result in dangling connections.

File: internal/destination/destination.go [hunk 6]
```diff
@@ -168,18 +170,34 @@ func (d *Destination) Open(ctx context.Context) error {
...
+		select {
+		case <-timeout.Done():
+			return recorded, errWriteTimeout
+		default:
+			if err := d.writer.Write(record); err != nil {
+				if attempts > d.config.RetryAttempts {
+					return recorded, err
+				}
+
+				time.Sleep(d.config.RetryWait)
```
[the remark this answers is not in the document]
Comment (nassor) [reply internal/destination/destination.go:191]: That is a good call; I added debug logs for the `context.Done` and the `timeout.Done`.

File: internal/destination/destination.go (hunk 5 above)
[the remark this answers is not in the document]
Comment (lovromazgon) [reply internal/destination/destination.go:174]: That's fine. I'm still wondering why we need a timeout context here? The context is going to make the number of retries non-deterministic, or in the worst case even cause the connector to fail the write. Imagine that we want to retry once (`RetryAttempts=1`) and wait 1 second between retries (`RetryWait=1s`), so the timeout will be set to 1 second. If the connection is slow or we have a big batch it might take more than 1 second to send all records, so we could hit the timeout before we manage to send everything.

File: internal/destination/destination.go (hunk 4 above)
Comment (lovromazgon) [reply internal/destination/destination.go:202]: That's what I was thinking of, yes, authentication errors and other things that are not recoverable. I'm not going to insist on adding this, but I do think it would be nice to think about what errors are recoverable.

File: internal/destination/config.go [hunk 7]
```diff
@@ -86,6 +90,10 @@ func (c *Config) parseFields(cfg map[string]string) error {
 			return fmt.Errorf("parse %q: %w", ConfigKeyRetryAttempts, err)
 		}
 
+		if retryAttempts == 0 {
+			retryAttempts = defaultRetryAttempts
+		}
```
Comment (lovromazgon) [inline internal/destination/config.go:95]: IMO we should also reject negative values.

File: internal/destination/destination.go [hunk 8]
```diff
@@ -131,42 +137,93 @@ func (d *Destination) Open(ctx context.Context) error {
...
+		select {
+		case <-ctx.Done():
+			err := ctx.Err()
+			sdk.Logger(ctx).Debug().
+				Int("record total", len(records)).
+				Int("record recorded", recorded).
+				Err(err).
+				Msg("write stopped by context before having all records recorded")
+
+			return recorded, nil
```
Comment (lovromazgon) [inline internal/destination/destination.go:191]: [Watch out](https://github.com/ConduitIO/conduit-connector-sdk/blob/main/destination.go#L57):
> Write must return a non-nil error if it returns n < len(r).

Besides, I don't think we need to listen to `ctx.Done` since the timeout context already wraps `ctx`. Unless we remove the timeout, then of course we need to have this case.

**Comment by nassor** [comment]
Reopening, because a bug on `Actions` (CI)

File: internal/destination/config.go (hunk 7 above)
Comment (nassor) [reply internal/destination/config.go:95]: or negative == retry forever (like most of clients' logic) ?

File: internal/destination/destination.go (hunk 8 above)
Comment (lovromazgon) [reply internal/destination/destination.go:187]: We still need to return an error, otherwise the SDK is going to regard this as a bug and [generate one for us](https://github.com/ConduitIO/conduit-connector-sdk/pull/80/files#diff-b0e314d1e24c22a62ecb712e94913d77bed15abfd75e80a0b61189c0abe17453R381).

File: internal/destination/config.go (hunk 7 above)
Comment (lovromazgon) [reply internal/destination/config.go:95]: Works for me as well. Maybe I'd just use `-1` as the magic value and return a validation error if it's any other negative number, just to be a bit more strict and prevent users from configuring infinite retries by mistake. That said, I don't think we should allow negative values for the wait between retries, that should be either 0 (default) or positive.

File: internal/destination/destination.go (hunk 6 above)
[the remark this answers is not in the document]
Comment (lovromazgon) [reply internal/destination/destination.go:194]: This was not addressed 😕

[the remark this answers is not in the document]
Comment (nassor) [reply internal/destination/destination.go:194]: Sorry, I marked it resolved without refreshing my page and looking at your next comment.

**Comment by nassor** [comment]
I removed all timeout/retry logic. The nats jetstream driver added that three months ago.

File: internal/destination/destination.go [hunk 9]
```diff
@@ -131,42 +132,79 @@ func (d *Destination) Open(ctx context.Context) error {
...
+func (d *Destination) Write(ctx context.Context, records []sdk.Record) (int, error) {
+	recorded := 0
+	for _, record := range records {
+		select {
+		case <-ctx.Done():
+			err := ctx.Err()
+			// if the context error has not a cause, err will have a null value
+			if err == nil {
+				err = context.Canceled
+			}
```
Comment (lovromazgon) [inline internal/destination/destination.go:177]: Can this even happen? The Go documentation states:
> If Done is closed, Err returns a non-nil error explaining why

File: internal/destination/destination.go [hunk 10]
```diff
@@ -131,42 +132,79 @@ func (d *Destination) Open(ctx context.Context) error {
...
+				Msg("write stopped by context before having all records recorded")
+
+			return recorded, err
+		default:
+			if err := d.writer.Write(record); err != nil {
+				sdk.Logger(ctx).Debug().
+					Int("record total", len(records)).
+					Int("record recorded", recorded).
+					Err(err).
+					Send()
```
Comment (lovromazgon) [inline internal/destination/destination.go:191]: Wait, so now we are just logging the error and continue writing the next record? And we even increase `recorded` so it will seem like the record was successfully written 😕 This could cause records to go missing.

File: internal/destination/destination.go (hunk 9 above)
Comment (nassor) [reply internal/destination/destination.go:177]: Not anymore. That line is "new" (last year). Fixing

File: internal/destination/config.go [hunk 11]
```diff
@@ -76,6 +76,10 @@ func (c *Config) parseFields(cfg map[string]string) error {
 			return fmt.Errorf("parse %q: %w", ConfigKeyRetryWait, err)
 		}
 
+		if retryWait <= 0 {
+			retryWait = defaultRetryWait
+		}
+
```
Comment (hariso) [inline internal/destination/config.go:82]: Great catch! IMHO though, it's better to return an error. If a user provided we should either accept it as it is or return an error. Replacing it with something else would be unexpected, at least to me.

Comment (nassor) [reply internal/destination/config.go]: I added some error returns for negative values and fix that 0 retries as a valid value.

File: internal/destination/config.go [hunk 12]
```diff
@@ -28,15 +29,18 @@ const (
...
 
-const (
 	// ConfigKeyRetryWait is a config name for a retry wait duration.
 	ConfigKeyRetryWait = "retryWait"
 	// ConfigKeyRetryAttempts is a config name for a retry attempts count.
 	ConfigKeyRetryAttempts = "retryAttempts"
 )
 
+var (
+	errNegativeRetryWait     = errors.New("DelayWait can't be a negative value")
```
Comment (lovromazgon) [inline internal/destination/config.go:40]:
```suggestion
	errNegativeRetryWait     = errors.New("retryWait can't be a negative value")
```

File: internal/destination/config.go [hunk 13]
```diff
@@ -28,15 +29,18 @@ const (
...
+	errNegativeRetryAttempts = errors.New("DelayWait can't be a negative value")
```
Comment (lovromazgon) [inline internal/destination/config.go:41]:
```suggestion
	errNegativeRetryAttempts = errors.New("retryAttempts can't be a negative value")
```

File: internal/destination/writer.go [hunk 14]
```diff
@@ -74,36 +70,18 @@ func NewWriter(params writerParams) (*Writer, error) {
...
-	// not redundant with Destination.Write
-	// writes can become unavailable when processing multiple records
-	if !w.canWrite.Load() {
-		return errWriteUnavailable
-	}
-
-	_, err := w.publisher.Publish(w.subject, record.Payload.After.Bytes(), w.publishOpts...)
+func (w *Writer) write(ctx context.Context, record sdk.Record) error {
+	publishOpts := append(w.publishOpts, nats.Context(ctx))
+	_, err := w.publisher.Publish(w.subject, record.Payload.After.Bytes(), publishOpts...)
```
Comment (lovromazgon) [inline internal/destination/writer.go:81]: I just noticed one last thing - we should publish `record.Bytes()` to nats, then the user can choose the [output format](https://conduit.io/docs/connectors/output-formats) (this functionality is provided by the SDK via a middleware).

**Review by lovromazgon — APPROVED** [review]
LGTM!
